# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/CliApp"
    schedule:
      interval: "daily"
    reviewers:
      - "BoBoBaSs84"
    assignees:
      - "BoBoBaSs84"
    groups:
      bb84-dependencies:
        patterns:
          - "BB84*"    
      mstest-dependencies:
        patterns:
          - "MSTest*"
      microsoft-extensions-dependencies:
        patterns:
          - "Microsoft.Extensions*"
  
  - package-ecosystem: "nuget"
    directory: "/GtaMod"
    schedule:
      interval: "daily"
    reviewers:
      - "BoBoBaSs84"
    assignees:
      - "BoBoBaSs84"
    groups:
      bb84-dependencies:
        patterns:
          - "BB84*"    
      mstest-dependencies:
        patterns:
          - "MSTest*"
      microsoft-extensions-dependencies:
        patterns:
          - "Microsoft.Extensions*"
  
  - package-ecosystem: "nuget"
    directory: "/winforms-net8"
    schedule:
      interval: "daily"
    reviewers:
      - "BoBoBaSs84"
    assignees:
      - "BoBoBaSs84"
    groups:
      bb84-dependencies:
        patterns:
          - "BB84*"    
      mstest-dependencies:
        patterns:
          - "MSTest*"
      microsoft-extensions-dependencies:
        patterns:
          - "Microsoft.Extensions*"

  - package-ecosystem: "nuget"
    directory: "/winforms-net48"
    schedule:
      interval: "daily"
    reviewers:
      - "BoBoBaSs84"
    assignees:
      - "BoBoBaSs84"
    groups:
      bb84-dependencies:
        patterns:
          - "BB84*"    
      mstest-dependencies:
        patterns:
          - "MSTest*"
      microsoft-extensions-dependencies:
        patterns:
          - "Microsoft.Extensions*"
  
  - package-ecosystem: "nuget"
    directory: "/wpf-net8"
    schedule:
      interval: "daily"
    reviewers:
      - "BoBoBaSs84"
    assignees:
      - "BoBoBaSs84"
    groups:
      bb84-dependencies:
        patterns:
          - "BB84*"    
      mstest-dependencies:
        patterns:
          - "MSTest*"
      microsoft-extensions-dependencies:
        patterns:
          - "Microsoft.Extensions*"
  
  - package-ecosystem: "nuget"
    directory: "/wpf-ef-net8"
    schedule:
      interval: "daily"
    reviewers:
      - "BoBoBaSs84"
    assignees:
      - "BoBoBaSs84"
    groups:
      bb84-dependencies:
        patterns:
          - "BB84*"    
      mstest-dependencies:
        patterns:
          - "MSTest*"
      microsoft-extensions-dependencies:
        patterns:
          - "Microsoft.Extensions*"
