<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType Condition="$(Configuration.Equals('Release'))">WinExe</OutputType>
		<OutputType Condition="$(Configuration.Equals('Debug'))">Exe</OutputType>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BB84.WinForms.Extensions" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	  <PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="System.Resources.Extensions" />
</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DomainName.Infrastructure\DomainName.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.Development.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="appsettings.Production.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>