//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainName.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DomainName.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (US).
        /// </summary>
        public static string Language_English_Name {
            get {
                return ResourceManager.GetString("Language.English.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string Language_English_ShortName {
            get {
                return ResourceManager.GetString("Language.English.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Language_French_Name {
            get {
                return ResourceManager.GetString("Language.French.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr-FR.
        /// </summary>
        public static string Language_French_ShortName {
            get {
                return ResourceManager.GetString("Language.French.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Language_German_Name {
            get {
                return ResourceManager.GetString("Language.German.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de-DE.
        /// </summary>
        public static string Language_German_ShortName {
            get {
                return ResourceManager.GetString("Language.German.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Language_Italian_Name {
            get {
                return ResourceManager.GetString("Language.Italian.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it-IT.
        /// </summary>
        public static string Language_Italian_ShortName {
            get {
                return ResourceManager.GetString("Language.Italian.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Language_Spanish_Name {
            get {
                return ResourceManager.GetString("Language.Spanish.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es-ES.
        /// </summary>
        public static string Language_Spanish_ShortName {
            get {
                return ResourceManager.GetString("Language.Spanish.ShortName", resourceCulture);
            }
        }
    }
}
